index:
    path: /
    defaults: { _controller: BlogBundle:Blog:blogViewAll }

blog_view:
    path: /blog/{id}
    defaults: { _controller: BlogBundle:Blog:blogView }
    requirements:
        id: \d+

blog_viewAll:
    path: /blog
    defaults: { _controller: BlogBundle:Blog:blogViewAll }

user_registration:
    path: /register
    defaults: { _controller: BlogBundle:Registration:register }

login:
    path: /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

admin:
    path: /admin
    defaults: { _controller: BlogBundle:Security:admin }

admin_blog:
    path: /admin/blog
    defaults: { _controller: BlogBundle:Security:blog }

admin_blog_edit:
    path: /admin/blog/{id}/edit
    defaults: { _controller: BlogBundle:Security:blogEdit }
    requirements:
        id: \d+

admin_blog_add:
    path: /admin/blog/add
    defaults: { _controller: BlogBundle:Security:blogAdd }
