index:
    path: /
    defaults: { _controller: BlogBundle:Blog:blogViewAll }

blog_view:
    path: /blog/{id}
    defaults: { _controller: BlogBundle:Blog:blogView }
    requirements:
        id: \d+

blog_viewAll:
    path: /blog
    defaults: { _controller: BlogBundle:Blog:blogViewAll }

user_registration:
    path: /register
    defaults: { _controller: BlogBundle:Registration:register }

login:
    path: /login
    defaults: { _controller: BlogBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout

admin:
    path: /admin
    defaults: { _controller: BlogBundle:Security:admin }

